---
title: "CatBoost"
author: "Yu Dong"
date: "9/16/2018"
output: html_document
---

## Set-up Catboost

Train Catboost with the original columns as the baseline.

```{r load package}
library(tidyverse)
library(catboost)

load('input/cleaned_all_data.RData')
```


```{r load data pool}
data_train = all_data[all_data$set== 'train',c(2,3,6:15, 17:21, 23, 25:29, 31)]
train_pool = catboost.load_pool(
    data = data_train[,-24],
    label = data_train[,24],
    cat_features = c(1,3,4,6,7,8,9,10,11,12,17,18,20,22,23))


data_test = all_data[all_data$set== 'test',c(2,3,6:15, 17:21, 23, 25:30)]
test_pool = catboost.load_pool(
    data = data_test[,-24],
    label = data_test[,24],
    cat_features = c(1,3,4,6,7,8,9,10,11,12,17,18,20,22,23))
```


```{r train model}
fit_params <- list(loss_function = 'RMSE',
                   iterations = 1000,
                   learning_rate = 0.01,
                   random_seed = 42,
                   one_hot_max_size = 100,
                   train_dir = 'train_dir')

model <- catboost.train(
    learn_pool = train_pool, 
    params = fit_params)
```

```{r prediction}
prediction <- catboost.predict(model, 
                               test_pool, 
                               prediction_type = 'RawFormulaVal')

prediction = ifelse(prediction <0, 0, prediction)
submission = data.frame(fullVisitorId = all_data[all_data$set== 'test',]$fullVisitorId, prediction = prediction)
submission$fullVisitorId = as.character(submission$fullVisitorId)

submission = submission %>% 
    group_by(fullVisitorId) %>%
    summarise(PredictedLogRevenue = log(sum(prediction)+1))

write.csv(submission, 'submission/submission091601.csv', row.names=FALSE)
```

Use log(revenue) as target column

```{r log}
all_data$logRevenue = log(all_data$transactionRevenue + 1)

data_train = all_data[all_data$set== 'train',c(2,3,6:15, 17:21, 23, 25:29, 31)]
train_pool = catboost.load_pool(
    data = data_train[,-24],
    label = data_train[,24],
    cat_features = c(1,3,4,6,7,8,9,10,11,12,17,18,20,22,23))


data_test = all_data[all_data$set== 'test',c(2,3,6:15, 17:21, 23, 25:29, 31)]
test_pool = catboost.load_pool(
    data = data_test[,-24],
    label = data_test[,24],
    cat_features = c(1,3,4,6,7,8,9,10,11,12,17,18,20,22,23))

###

fit_params <- list(loss_function = 'RMSE',
                   iterations = 2000,
                   learning_rate = 0.005,
                   random_seed = 42,
                   one_hot_max_size = 100,
                   train_dir = 'train_dir')

model <- catboost.train(
    learn_pool = train_pool, 
    params = fit_params)

###

prediction <- catboost.predict(model, 
                               test_pool, 
                               prediction_type = 'RawFormulaVal')

prediction = ifelse(exp(prediction) - 1 <0, 0, exp(prediction) - 1)
submission = data.frame(fullVisitorId = all_data[all_data$set== 'test',]$fullVisitorId, prediction = prediction)

submission = submission %>% 
    group_by(fullVisitorId) %>%
    summarise(PredictedLogRevenue = log(sum(prediction)+1))

submission$PredictedLogRevenue = as.character(submission$PredictedLogRevenue)

write.csv(submission, 'submission/submission091602.csv', row.names=FALSE)

```

```{r fix bounced session}
## fix bounced session revenue to always 0

submission = data.frame(
    fullVisitorId = all_data[all_data$set== 'test',]$fullVisitorId, 
    bounces = all_data[all_data$set== 'test',]$bounces,
    prediction = prediction)

submission$prediction = ifelse(submission$bounces == 1, 0, submission$prediction)

submission$bounces = NULL

submission = submission %>% 
    group_by(fullVisitorId) %>%
    summarise(PredictedLogRevenue = log(sum(prediction)+1))

submission$PredictedLogRevenue = as.character(submission$PredictedLogRevenue)

write.csv(submission, 'submission/submission091603.csv', row.names=FALSE)

```


```{r predict with unbounced session}
all_data$logRevenue = log(all_data$transactionRevenue + 1)

data_train = all_data %>%
    filter(set== 'train',
           bounces == 0) %>%
    select(c(2,3,6:15, 17:21, 23, 25:29, 31))

train_pool = catboost.load_pool(
    data = data_train[,-24],
    label = data_train[,24],
    cat_features = c(1,3,4,6,7,8,9,10,11,12,17,18,20,22,23))


data_test = all_data %>%
    filter(set== 'test',
           bounces == 0) %>%
    select(c(2,3,6:15, 17:21, 23, 25:29, 31))

test_pool = catboost.load_pool(
    data = data_test[,-24],
    label = data_test[,24],
    cat_features = c(1,3,4,6,7,8,9,10,11,12,17,18,20,22,23))

###

fit_params <- list(loss_function = 'RMSE',
                   iterations = 2000,
                   learning_rate = 0.005,
                   random_seed = 42,
                   one_hot_max_size = 100,
                   train_dir = 'train_dir')

model <- catboost.train(
    learn_pool = train_pool, 
    params = fit_params)

###

prediction <- catboost.predict(model, 
                               test_pool, 
                               prediction_type = 'RawFormulaVal')

prediction = ifelse(exp(prediction) - 1 <0, 0, exp(prediction) - 1)



submission = data.frame(fullVisitorId = filter(all_data, set== 'test', bounces == 0)$fullVisitorId, prediction = prediction)

submission = rbind(submission, 
                   data.frame(
                       fullVisitorId = filter(all_data, 
                              set== 'test', 
                              bounces == 1)$fullVisitorId, 
                       prediction = 0))

submission = submission %>% 
    group_by(fullVisitorId) %>%
    summarise(PredictedLogRevenue = log(sum(prediction)+1))

submission$PredictedLogRevenue = as.character(submission$PredictedLogRevenue)

write.csv(submission, 'submission/submission091604.csv', row.names=FALSE)

```

